let ListItem=[{
    bool:1,
    height:96,
    key:"1",
    img:"red",
    tittle:"家园东北烧烤",
    range:"350米",
    starNumber:1,
    infoList:[{key: '减',valInfo:"减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"}],
    actityNumber:2
},{
    bool:1,
    height:96,
    key:"2",
    img:"blue",
    tittle:"家园东南烧烤",
    range:"320米",
    starNumber:2,
    infoList:[{key: '减',valInfo:"真的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:3},{
    bool:1,
    height:96,
    key:"3",
    img:"green",
    tittle:"家园西南烧烤",
    range:"360米",
    starNumber:3,
    infoList:[{key: '减',valInfo:"假的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:4
},{
    bool:1,
    height:96,
    key:"4",
    img:"pink",
    tittle:"家园西北烧烤",
    range:"370米",
    starNumber:4,
    infoList:[{key: '减',valInfo:"虚的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:5
},{
    bool:1,
    height:96,
    key:"5",
    img:"#e5eaf6",
    tittle:"家园西北烧烤1",
    range:"390米",
    starNumber:5,
    infoList:[{key: '减',valInfo:"实的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:6
},{
    bool:1,
    height:96,
    key:"6",
    img:"#e5eaf6",
    tittle:"家园西北烧烤1",
    range:"390米",
    starNumber:5,
    infoList:[{key: '减',valInfo:"实的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:6
},{
    bool:1,
    height:96,
    key:"7",
    img:"#e5eaf6",
    tittle:"家园西北烧烤1",
    range:"390米",
    starNumber:5,
    infoList:[{key: '减',valInfo:"实的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:6
},{
    bool:1,
    height:96,
    key:"8",
    img:"#e5eaf6",
    tittle:"家园西北烧烤1",
    range:"390米",
    starNumber:5,
    infoList:[{key: '减',valInfo:"实的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:6
},{
    bool:1,
    height:96,
    key:"9",
    img:"#e5eaf6",
    tittle:"家园西北烧烤1",
    range:"390米",
    starNumber:5,
    infoList:[{key: '减',valInfo:"实的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:6
},{
    bool:1,
    height:96,
    key:"10",
    img:"#e5eaf6",
    tittle:"家园西北烧烤1",
    range:"390米",
    starNumber:5,
    infoList:[{key: '减',valInfo:"实的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:6
}];



let newListItem=[{
    bool:1,
    height:96,
    key:"1",
    img:"pink",
    tittle:"家园东北烧烤_1222",
    range:"350米",
    starNumber:1,
    infoList:[{key: '减',valInfo:"减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"}],
    actityNumber:2
},{
    bool:1,
    height:96,
    key:"2",
    img:"red",
    tittle:"家园东南烧烤33333",
    range:"320米",
    starNumber:2,
    infoList:[{key: '减',valInfo:"真的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:3},{
    bool:1,
    height:96,
    key:"3",
    img:"black",
    tittle:"家园西南烧烤_4444",
    range:"360米",
    starNumber:3,
    infoList:[{key: '减',valInfo:"假的减价啦,快来买是不是傻啊"},
        {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
        {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
        {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
        {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
    actityNumber:4
},
    {
        key:"4",
        bool:1,
        height:96,
        img:"red",
        tittle:"家园西北烧烤_7878",
        range:"370米",
        starNumber:4,
        infoList:[{key: '减',valInfo:"虚的减价啦,快来买是不是傻啊"},
            {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
            {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
            {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
            {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
        actityNumber:5
    },{
        bool:1,
        height:96,
        key:"5",
        img:"#e5eaf6",
        tittle:"家园西北烧烤18989",
        range:"390米",
        starNumber:5,
        infoList:[{key: '减',valInfo:"实的减价啦,快来买是不是傻啊"},
            {key: '折',valInfo:"打折啦,快来买是不是傻啊"},
            {key: '银',valInfo:"银行啦,快来买是不是傻啊"},
            {key: '赠',valInfo:"赠品啦,快来买是不是傻啊"},
            {key: '首',valInfo:"首付啦,快来买是不是傻啊"}],
        actityNumber:6
    }];

export {ListItem,newListItem}